### ISSUE TITLE
Scripts do not run.

### ISSUE THREAD

**Issue by coderlcd** [SIUE-DevOps/Vagrant-Files#2]
I created two bash scripts on my branch (/logan). One for a Gnome Desktop, which we can use if we turn GUI=true so that we can run GUI Docker Containers. The other script is for installing docker. These scripts can be found in:
bootstrp_env/roles/install-tools/tasks/

When the script portion of the ansible file is ran, ansible does not execute the script, but instead just stalls without executing the script.

We need to find a way to get these scripts (and potentially others) to run so that we can simplify the installs of the tools. 

Potential Options to resolve?:
1. Fix script issue
2. Convert bash script to ansible modules

**Comment by HauptJ** [comment]
Going to try using Steves Docker install script. If his works, docker.sh will be deleted.
